[package]
name = "mads-example-posts-crud"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
publish = false

[workspace]

[dependencies]
mads = { version = "=0.9.0", default-features = false, features = ["http", "runtime-tokio"] }
mads-persistence = { version = "=0.9.0", features = ["sea-orm-postgres"] }
sea-orm = { version = "=2.0.0", default-features = false, features = ["macros", "sqlx-postgres", "runtime-tokio-rustls"] }
serde = { version = "1", features = ["derive"] }
