[package]
name = "mads-extra"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
description = "Extension boundary for optional MADS.rs framework capabilities"

[dependencies]
mads-core = { path = "../mads-core", version = "=0.8.0-beta.1" }

[lints]
workspace = true
