[package]
name = "mads-example-protected-route"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
publish = false

[workspace]

[dependencies]
mads = { version = "=0.9.0", default-features = false, features = ["http", "jwt", "logger", "runtime-tokio"] }
serde = { version = "1", features = ["derive"] }
