use crate::database::{
    diff::{MigrationPlan, MigrationWarning, Operation, review_warnings},
    schema::{ColumnSchema, PgType, QualifiedTableName, TableSchema},
};

const REVIEW_HEADER: [&str; 2] = [
    "-- Generated by MADS.rs. Review before applying.",
    "-- Unsupported defaults, indexes, checks, triggers, and FK policies are not synthesized.",
];

/// Fully rendered, review-required SQL for one migration shape plan.
pub(crate) struct RenderedMigration {
    /// Forward SQL that transforms the captured live shape toward the desired shape.
    pub(crate) up_sql: String,
    /// Exact typed inverse SQL that transforms the desired shape toward the captured live shape.
    pub(crate) down_sql: String,
    /// Deterministic manual-review warnings shared with the public CLI outcome.
    pub(crate) warnings: Vec<MigrationWarning>,
}

/// Renders a typed schema plan without accepting raw SQL identifiers or types.
pub(crate) fn render_migration(plan: &MigrationPlan) -> RenderedMigration {
    let warnings = review_warnings(plan.warnings());
    let warning_lines = warning_lines(&warnings);
    RenderedMigration {
        up_sql: render_document(&warning_lines, plan.up()),
        down_sql: render_document(&warning_lines, plan.down()),
        warnings,
    }
}

impl PgType {
    /// Renders this validated PostgreSQL type using its canonical SQL spelling.
    pub(crate) fn to_sql(&self) -> String {
        match self {
            Self::Bool => "boolean".into(),
            Self::SmallInt => "smallint".into(),
            Self::Integer => "integer".into(),
            Self::BigInt => "bigint".into(),
            Self::Real => "real".into(),
            Self::DoublePrecision => "double precision".into(),
            Self::Numeric => "numeric".into(),
            Self::Text => "text".into(),
            Self::VarChar(length) => render_length_limited_type("varchar", *length),
            Self::Char(length) => render_length_limited_type("char", *length),
            Self::Bytea => "bytea".into(),
            Self::Date => "date".into(),
            Self::Time => "time".into(),
            Self::Timestamp => "timestamp".into(),
            Self::TimestampWithTimeZone => "timestamp with time zone".into(),
            Self::Json => "json".into(),
            Self::Jsonb => "jsonb".into(),
            Self::Uuid => "uuid".into(),
            Self::Inet => "inet".into(),
            Self::Cidr => "cidr".into(),
            Self::MacAddr => "macaddr".into(),
            Self::Array(element) => format!("{}[]", element.to_sql()),
        }
    }
}

fn render_length_limited_type(name: &str, length: Option<u32>) -> String {
    match length {
        Some(length) => format!("{name}({length})"),
        None => name.into(),
    }
}

fn quote_identifier(identifier: &str) -> String {
    format!("\"{}\"", identifier.replace('"', "\"\""))
}

fn qualified(table: &QualifiedTableName) -> String {
    format!(
        "{}.{}",
        quote_identifier(&table.schema),
        quote_identifier(&table.table)
    )
}

fn normalized_warnings(warnings: &[MigrationWarning]) -> Vec<String> {
    warning_lines(&review_warnings(warnings))
}

fn warning_lines(warnings: &[MigrationWarning]) -> Vec<String> {
    warnings
        .iter()
        .map(|warning| format!("{}: {}", warning.subject, warning.message))
        .collect()
}

fn render_document(warnings: &[String], operations: &[Operation]) -> String {
    let mut lines = REVIEW_HEADER.map(str::to_owned).to_vec();
    lines.extend(
        warnings
            .iter()
            .map(|warning| format!("-- WARNING: {warning}")),
    );
    if !operations.is_empty() {
        lines.push(String::new());
        lines.extend(operations.iter().map(render_operation));
    }
    normalize_newlines(lines.join("\n"))
}

fn render_operation(operation: &Operation) -> String {
    match operation {
        Operation::CreateTable(table) => render_create_table(table),
        Operation::DropTable(table) => format!("DROP TABLE {};", qualified(&table.name)),
        Operation::AddColumn { table, column } => format!(
            "ALTER TABLE {} ADD COLUMN {};",
            qualified(table),
            render_column(column)
        ),
        Operation::DropColumn { table, column } => format!(
            "ALTER TABLE {} DROP COLUMN {};",
            qualified(table),
            quote_identifier(&column.name)
        ),
        Operation::AlterType {
            table, column, to, ..
        } => {
            let column = quote_identifier(column);
            let sql_type = to.to_sql();
            format!(
                "ALTER TABLE {} ALTER COLUMN {column} TYPE {sql_type} USING {column}::{sql_type};",
                qualified(table)
            )
        }
        Operation::SetNotNull { table, column } => format!(
            "ALTER TABLE {} ALTER COLUMN {} SET NOT NULL;",
            qualified(table),
            quote_identifier(column)
        ),
        Operation::DropNotNull { table, column } => format!(
            "ALTER TABLE {} ALTER COLUMN {} DROP NOT NULL;",
            qualified(table),
            quote_identifier(column)
        ),
    }
}

fn render_create_table(table: &TableSchema) -> String {
    let mut declarations = table.columns.iter().map(render_column).collect::<Vec<_>>();
    if !table.primary_key.is_empty() {
        let primary_key = table
            .primary_key
            .iter()
            .map(|column| quote_identifier(column))
            .collect::<Vec<_>>()
            .join(", ");
        declarations.push(format!("PRIMARY KEY ({primary_key})"));
    }
    format!(
        "CREATE TABLE {} (\n    {}\n);",
        qualified(&table.name),
        declarations.join(",\n    ")
    )
}

fn render_column(column: &ColumnSchema) -> String {
    let nullability = if column.nullable { "" } else { " NOT NULL" };
    format!(
        "{} {}{nullability}",
        quote_identifier(&column.name),
        column.sql_type.to_sql(),
    )
}

fn normalize_newlines(document: String) -> String {
    let document = document.replace("\r\n", "\n").replace('\r', "\n");
    format!("{}\n", document.trim_end_matches('\n'))
}

#[cfg(test)]
mod tests {
    use super::{
        normalized_warnings, qualified, quote_identifier, render_document, render_operation,
    };
    use crate::database::{
        diff::{MigrationWarning, Operation},
        schema::{ColumnSchema, PgType, QualifiedTableName, TableSchema},
    };

    const CREATE_USERS_UP: &str =
        include_str!("../../tests/fixtures/schema/expected/create_users_up.sql");
    const CREATE_USERS_DOWN: &str =
        include_str!("../../tests/fixtures/schema/expected/create_users_down.sql");

    #[test]
    fn quotes_identifiers_and_qualified_table_names() {
        assert_eq!(quote_identifier("user\"events"), "\"user\"\"events\"");
        assert_eq!(
            qualified(&QualifiedTableName::new("audit", "events")),
            "\"audit\".\"events\""
        );
    }

    #[test]
    fn renders_canonical_scalar_and_array_types() {
        assert_eq!(PgType::VarChar(Some(255)).to_sql(), "varchar(255)");
        assert_eq!(PgType::VarChar(None).to_sql(), "varchar");
        assert_eq!(PgType::Char(Some(8)).to_sql(), "char(8)");
        assert_eq!(
            PgType::TimestampWithTimeZone.to_sql(),
            "timestamp with time zone"
        );
        assert_eq!(PgType::Array(Box::new(PgType::Text)).to_sql(), "text[]");
        assert_eq!(
            PgType::Array(Box::new(PgType::Array(Box::new(PgType::Uuid)))).to_sql(),
            "uuid[][]"
        );
    }

    #[test]
    fn renders_create_table_as_the_byte_exact_golden_fixture() {
        let sql = render_document(&[], &[Operation::CreateTable(users_table())]);
        assert_eq!(sql, CREATE_USERS_UP);
    }

    #[test]
    fn renders_drop_table_as_the_byte_exact_golden_fixture() {
        let sql = render_document(&[], &[Operation::DropTable(users_table())]);
        assert_eq!(sql, CREATE_USERS_DOWN);
    }

    #[test]
    fn renders_add_and_drop_column_without_synthetic_semantics() {
        let users = QualifiedTableName::new("public", "users");
        let email = column("email", PgType::VarChar(Some(255)), false, 1);

        assert_eq!(
            render_operation(&Operation::AddColumn {
                table: users.clone(),
                column: email.clone(),
            }),
            "ALTER TABLE \"public\".\"users\" ADD COLUMN \"email\" varchar(255) NOT NULL;"
        );
        assert_eq!(
            render_operation(&Operation::DropColumn {
                table: users,
                column: email,
            }),
            "ALTER TABLE \"public\".\"users\" DROP COLUMN \"email\";"
        );
    }

    #[test]
    fn renders_type_and_nullability_changes_with_quoted_columns() {
        let users = QualifiedTableName::new("public", "users");
        assert_eq!(
            render_operation(&Operation::AlterType {
                table: users.clone(),
                column: "display\"name".into(),
                from: PgType::Text,
                to: PgType::VarChar(Some(255)),
            }),
            "ALTER TABLE \"public\".\"users\" ALTER COLUMN \"display\"\"name\" TYPE varchar(255) USING \"display\"\"name\"::varchar(255);"
        );
        assert_eq!(
            render_operation(&Operation::SetNotNull {
                table: users.clone(),
                column: "email".into(),
            }),
            "ALTER TABLE \"public\".\"users\" ALTER COLUMN \"email\" SET NOT NULL;"
        );
        assert_eq!(
            render_operation(&Operation::DropNotNull {
                table: users,
                column: "email".into(),
            }),
            "ALTER TABLE \"public\".\"users\" ALTER COLUMN \"email\" DROP NOT NULL;"
        );
    }

    #[test]
    fn normalizes_sorts_and_deduplicates_warning_strings_for_comments() {
        let warnings = normalized_warnings(&[
            MigrationWarning {
                subject: "public.users.email".into(),
                message: "cast review".into(),
            },
            MigrationWarning {
                subject: "public.users".into(),
                message: "data review".into(),
            },
            MigrationWarning {
                subject: "public.users.email".into(),
                message: "cast review".into(),
            },
        ]);
        assert_eq!(
            warnings,
            [
                "public.users: data review",
                "public.users.email: cast review"
            ]
        );
        assert_eq!(
            render_document(&warnings, &[]),
            concat!(
                "-- Generated by MADS.rs. Review before applying.\n",
                "-- Unsupported defaults, indexes, checks, triggers, and FK policies are not synthesized.\n",
                "-- WARNING: public.users: data review\n",
                "-- WARNING: public.users.email: cast review\n"
            )
        );
    }

    #[test]
    fn escapes_warning_line_breaks_before_exposing_or_rendering_them() {
        let warnings = normalized_warnings(&[
            MigrationWarning {
                subject: "public.users\nDROP TABLE \"public\".\"accounts\";".into(),
                message: "review\rthis\ncarefully".into(),
            },
            MigrationWarning {
                subject: "public.users\\nDROP TABLE \"public\".\"accounts\";".into(),
                message: "review\\rthis\\ncarefully".into(),
            },
        ]);
        let expected =
            "public.users\\nDROP TABLE \"public\".\"accounts\";: review\\rthis\\ncarefully";

        assert_eq!(warnings, [expected]);

        let up_sql = render_document(&warnings, &[]);
        let down_sql = render_document(&warnings, &[]);
        for document in [up_sql, down_sql] {
            assert!(document.contains(&format!("-- WARNING: {expected}")));
            assert!(!document.contains("\r"));
            assert!(!document.contains("\nDROP TABLE \"public\".\"accounts\";"));
        }
    }

    fn users_table() -> TableSchema {
        TableSchema {
            name: QualifiedTableName::new("public", "users"),
            columns: vec![
                column("id", PgType::BigInt, false, 0),
                column("email", PgType::VarChar(Some(255)), false, 1),
                column("nickname", PgType::Text, true, 2),
            ],
            primary_key: vec!["id".into()],
        }
    }

    fn column(name: &str, sql_type: PgType, nullable: bool, ordinal: usize) -> ColumnSchema {
        ColumnSchema {
            name: name.into(),
            sql_type,
            nullable,
            ordinal,
        }
    }
}
